default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default
   adapter: postgresql
  encoding: unicode
  database: production
  host: <%= ENV['DATABASE_HOST'] %>
  pool: 5
